### ISSUE TITLE
Install dependencies automatically or check if installed

### ISSUE THREAD

**Issue by ShadowOfPripyat** [ShadowOfPripyat/wave-depressor#2]
in some machines, these libraries are not installed by default, so we should find a way to install them without a getting lot of delay.

**Comment by umut-er** [comment]
Argparse, sys and re are all part of the python standard library and they should come preinstalled with any python distribution. As for pysndfx, I propose:
```diff
- os.system("pip install pysndfx")
- os.system("pip install argparse")
- os.system("pip install sys")
- os.system("pip install re")
- os.system("clear")

+ try:
+     from pysndfx import AudioEffectsChain
+ except ModuleNotFoundError:
+     os.system("pip install pysndfx")
+     from pysndfx import AudioEffectsChain
import argparse
import sys
import re
```
This way, you waste almost no time if user already has the package. Then again, I think you should ask before you install any packages (Inform me if you want this feature). I can work on this if you want. Have a nice day!

**Comment by ShadowOfPripyat** [comment]
Thanks! Sorry for not doing it on time but have a nice day you too!
