### ISSUE TITLE
Make a better README.md

### ISSUE THREAD

**Issue by ShadowOfPripyat** [ShadowOfPripyat/wave-depressor#5]
Honestly i'm a bit lazy to make a good readme. I also dont know markdown so...
Here's a job for ya m8

**Comment by pranit9000** [comment]
hey, can you please assign this to me

**Comment by InsightCracker** [comment]
Can I work on it

**Comment by ShadowOfPripyat** [comment]
You both make the README.md and the best will be applied. If you're lucky both will get rewarded

**Comment by InsightCracker** [comment]
Thanks for the assignment, I'll make a PR soon

**Comment by InsightCracker** [comment]
@ShadowOfPripyat  I have made a pull request, kindly check it out
